config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-ams-library:
      branch: master
      repo: https://github.com/ARGOeu/argo-ams-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cardinal-goat.sh
        container: qc.acc_chewy-bistre-dolphin
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-ams-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cyan-dollar.sh
        container: qc.doc_scanty-periwinkle-termite
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-magnolia-quokka.sh
        container: qc.doc_snippy-turquoise-axolotl
      github.com/ARGOeu/argo-ams-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-teal-crocodile.sh
        container: qc.doc_hazy-carmine-newfoundland
      github.com/ARGOeu/argo-ams-library restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-blue-ant.sh
        container: qc.doc_snoopy-cyan-caracal
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-ams-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-amber-albatross.sh
        container: qc.lic_chummy-blue-wombat
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-ams-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-khaki-lizard.sh
        container: qc.sec_shaggy-burgundy-cuscus
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-ams-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-wisteria-hedgehog.sh
        container: qc.sty_blurry-persimmon-collie
      github.com/ARGOeu/argo-ams-library hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-black-drever.sh
        container: qc.sty_frumpy-burgundy-angelfish
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-ams-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-ochre-whale.sh
        container: qc.uni_pretty-coral-liger
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-ams-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-auburn-anteater.sh
        container: qc.ver_fuzzy-linen-beetle
timeout: 5400
