config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-ams-library:
      branch: master
      repo: https://github.com/ARGOeu/argo-ams-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-rose-tarantula.sh
        container: qc.acc_homey-turquoise-wolf
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-ams-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-eggplant-hyena.sh
        container: qc.doc_stealthy-vermilion-bear
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-aquamarine-bonobo.sh
        container: qc.doc_queasy-russet-gerbil
      github.com/ARGOeu/argo-ams-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cinnabar-dachshund.sh
        container: qc.doc_scummy-goldenrod-wombat
      github.com/ARGOeu/argo-ams-library restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-brass-gecko.sh
        container: qc.doc_homely-pink-reindeer
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-ams-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-silver-akbash.sh
        container: qc.lic_woozy-chestnut-chamois
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-ams-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-crimson-chinook.sh
        container: qc.sec_snoopy-champagne-jellyfish
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-ams-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-tan-macaque.sh
        container: qc.sty_craggy-silver-ray
      github.com/ARGOeu/argo-ams-library hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-wheat-eleuth.sh
        container: qc.sty_scaly-aqua-birman
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-ams-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-peach-dunker.sh
        container: qc.uni_slimy-brown-sponge
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-ams-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-blue-retriever.sh
        container: qc.ver_silly-thistle-salamander
timeout: 5400
