config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-ams-library:
      branch: master
      repo: https://github.com/ARGOeu/argo-ams-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-magnolia-ant.sh
        container: qc.acc_freaky-tan-dugong
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-ams-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-grey-beagle.sh
        container: qc.doc_wimpy-aqua-bonobo
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-black-dhole.sh
        container: qc.doc_baggy-vermilion-audemer
      github.com/ARGOeu/argo-ams-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-gold-maltese.sh
        container: qc.doc_pretty-tomato-loon
      github.com/ARGOeu/argo-ams-library restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-blue-setter.sh
        container: qc.doc_skanky-flax-lobster
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-ams-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-turquoise-capybara.sh
        container: qc.lic_lousy-blue-spitz
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-ams-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-red-buzzard.sh
        container: qc.sec_boozy-myrtle-leopard
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-ams-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-charcoal-kakapo.sh
        container: qc.sty_freaky-ruby-dachshund
      github.com/ARGOeu/argo-ams-library hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-plum-mongrel.sh
        container: qc.sty_hazy-pink-zebu
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-ams-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-pear-chicken.sh
        container: qc.uni_leaky-pear-gharial
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-ams-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-thistle-foxhound.sh
        container: qc.ver_ready-green-penguin
timeout: 5400
