config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-ams-library:
      branch: master
      repo: https://github.com/ARGOeu/argo-ams-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cornflower-ant.sh
        container: qc.acc_stealthy-xanthic-blue
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-ams-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-carmine-dingo.sh
        container: qc.doc_ready-violet-avocet
      github.com/ARGOeu/argo-ams-library git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-rust-otter.sh
        container: qc.doc_boozy-coral-owl
      github.com/ARGOeu/argo-ams-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-peach-skunk.sh
        container: qc.doc_shabby-pear-vulture
      github.com/ARGOeu/argo-ams-library restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-violet-malamute.sh
        container: qc.doc_lovely-cobalt-stingray
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-ams-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-periwinkle-dollar.sh
        container: qc.lic_grumpy-plum-whale
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-ams-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-taupe-squirt.sh
        container: qc.sec_wheezy-peach-hornet
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-ams-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-carmine-mau.sh
        container: qc.sty_craggy-grey-caiman
      github.com/ARGOeu/argo-ams-library hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-copper-buffalo.sh
        container: qc.sty_frumpy-chocolate-chimpanzee
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-ams-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-flax-hornet.sh
        container: qc.uni_blurry-carmine-guppy
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-ams-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-asparagus-wombat.sh
        container: qc.ver_lovely-lavender-angelfish
timeout: 5400
